#!/usr/bin/env python3
import os
import yaml
import frontmatter
from pathlib import Path

GITHUB_REPO_URL = "https://github.com/HY-LiYihan/liyihan.net_markdown/blob/main/"
SITE_URL = "https://liyihan.net"
VERSION_FILE = 'VERSION'
VERSIONS_DIR = 'versions'

CATEGORIES = {
    'Linux': 'Linux',
    '工具': '工具',
    '开发': '开发'
}

EMOJI_MAP = {
    'Linux': '🐧',
    '工具': '🛠️',
    '开发': '💻'
}

def parse_markdown_file(filepath):
    try:
        post = frontmatter.load(filepath)
        return {
            'title': post.get('title', Path(filepath).stem),
            'path': filepath,
            'categories': post.get('categories', []),
            'tags': post.get('tags', [])
        }
    except Exception as e:
        print(f"Error parsing {filepath}: {e}")
        return None

def scan_directory(category_name, dir_path):
    files = []
    if not os.path.exists(dir_path):
        return files

    for root, dirs, filenames in os.walk(dir_path):
        for filename in filenames:
            if filename.endswith('.md'):
                filepath = os.path.join(root, filename)
                post_info = parse_markdown_file(filepath)
                if post_info:
                    # 计算相对于项目根目录的路径
                    rel_path = os.path.relpath(filepath, '.')
                    post_info['path'] = rel_path
                    files.append(post_info)

    return files

def generate_readme():
    readme_content = "# LiYiHan Knowledge Base\n\n"
    readme_content += "本知识库汇集个人技术笔记与速查手册，访问完整版请至 [liyihan.net](https://liyihan.net)\n\n"

    # 确定要扫描的目录
    if os.path.exists(VERSION_FILE):
        current_version = open(VERSION_FILE, 'r').read().strip()
        version_info_path = os.path.join(VERSIONS_DIR, current_version, 'version_info.yaml')

        # 添加版本管理部分
        readme_content += "## 📦 版本管理\n\n"
        readme_content += f"**当前版本**: `{current_version}`"

        if os.path.exists(version_info_path):
            with open(version_info_path, 'r', encoding='utf-8') as f:
                version_info = yaml.safe_load(f)
                created_at = version_info.get('created_at', '')[:10]
                readme_content += f" ({created_at})\n\n"
                readme_content += f"- 总文章数: {version_info.get('total_articles', 0)} 篇\n"
                if version_info.get('previous_version'):
                    previous = version_info['previous_version']
                    readme_content += f"- 上一个版本: [`{previous}`]({GITHUB_REPO_URL}versions/{previous}/)\n"
        else:
            readme_content += "\n"

        readme_content += f"- [查看所有版本]({GITHUB_REPO_URL}versions/)\n\n"
        readme_content += "---\n\n"

        # 扫描当前版本目录
        base_dir = os.path.join(VERSIONS_DIR, current_version)
    else:
        base_dir = '.'

    # 按分类展示
    for category_name, dir_name in CATEGORIES.items():
        category_path = os.path.join(base_dir, dir_name)
        files = scan_directory(category_name, category_path)

        emoji = EMOJI_MAP.get(category_name, '')
        readme_content += f"## {emoji} {category_name}\n"

        if files:
            for file_info in files:
                rel_path = file_info['path'].replace('\\', '/')
                full_url = GITHUB_REPO_URL + rel_path
                readme_content += f"- [{file_info['title']}]({full_url})\n"
        else:
            readme_content += "*暂无内容*\n"

        readme_content += "\n"

    readme_content += "---\n\n*Auto-generated by scripts/generate_readme.py*"

    return readme_content

def main():
    readme_content = generate_readme()

    with open('README.md', 'w', encoding='utf-8') as f:
        f.write(readme_content)

    print("[OK] README.md generated")

if __name__ == '__main__':
    main()
